version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: pg_apialuno
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root123
      POSTGRES_DB: apialuno
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - rede_apialuno

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin_apialuno
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@apilorde.com
      PGADMIN_DEFAULT_PASSWORD: root123
    ports:
      - "5050:80"
    depends_on:
      - postgres
    networks:
      - rede_apialuno

volumes:
  postgres_data:

networks:
  rede_apialuno:
    driver: bridge